language: node_js
node_js:
  - "7.5.0"
dist: trusty
sudo: false
notifications:
  email: false
cache:
  directories:
    - node_modules
before_install:
  - npm explore npm -g -- npm install node-gyp@latest
install: npm install
